config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root to: 'homes#home'
  get "home/about", to: "homes#about"

  resources :users, only: [:show, :edit, :update, :create, :index, :destroy, :new]

  resources :books do
    resource :favorites, only: [:create, :destroy]
    resources :book_comments, only: [:create, :destroy]
  end
  #コメント、いいねはbooksの中にネストすることで入れ子構造を確立

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord

  belongs_to :user

  has_many :favorites, dependent: :destroy
  has_many :book_comments, dependent: :destroy

  validates :title, presence: true
  validates :body, presence: true, length: { maximum: 200 }

  def favorited_by?(user) #既にいいねされているか。favorited_by?メソッド
    favorites.where(user_id: user.id).exists?
  end

end

app/models/book_comment.rb
class BookComment < ApplicationRecord
  belongs_to :user
  belongs_to :book

  validates :comment, presence: true
end

app/models/favorite.rb
class Favorite < ApplicationRecord

  belongs_to :user
  belongs_to :book
  
  validates_uniqueness_of :book_id, scope: :user_id
  #一人につき１いいね
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :books, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :book_comments, dependent: :destroy
  attachment :profile_image



  validates :name, presence: true, uniqueness: true, length: { in: 2..20 }
  validates :introduction, length: { maximum: 50 }

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  #protect_from_forgery with: :exception
  before_action :authenticate_user!,except: [:home, :about]
  before_action :configure_permitted_parameters, if: :devise_controller?


  def after_sign_in_path_for(resource)
    flash[:notice] = 'You have signed in successfully.'
    user_path(resource)
  end


  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :profile_image, :email])
    devise_parameter_sanitizer.permit(:sign_in, keys: [:name])
  end
end

app/controllers/book_comments_controller.rb
class BookCommentsController < ApplicationController
  def create
    book = Book.find(params[:book_id])
    comment = current_user.book_comments.new(book_comment_params)
    comment.book_id = book.id
    comment.save
    redirect_back(fallback_location: root_path)
  end

  def destroy
    BookComment.find_by(id: params[:id], book_id: params[:book_id]).destroy
    #BookComment.find_by(id: params[:id]).destroy
    redirect_back(fallback_location: root_path)
  end

  private

  def book_comment_params
    params.require(:book_comment).permit(:comment)
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def new
    @book = Book.new
  end

  def create
    @user = current_user
    @users = User.all
    @books = Book.all
    @book = Book.new(book_params)
    @book.user_id = current_user.id

    if @book.save
     redirect_to book_path(@book.id), notice: 'You have created book successfully'
    else
     render :index
    end
  end

  def index
    @book = Book.new
    @books = Book.all
    @users = User.all
    @user = current_user
  end

  def show
    @book = Book.find(params[:id])
    @books = Book.new
    @user = @book.user
    @book_comment = BookComment.new
  end

  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    redirect_to books_path
  end

  def edit
    @book = Book.find(params[:id])
    if @book.user == current_user
      render :edit
    else
        redirect_to books_path
    end
  end


  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
    	 redirect_to book_path(@book), notice:  "You have updated book successfully"
    else
       render :edit
    end
  end

  private
  def book_params
    params.require(:book).permit(:title, :body)
  end

end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController

  def create
    book = Book.find(params[:book_id])
    favorite = current_user.favorites.new(book_id: params[:book_id])
    favorite.save
    redirect_back(fallback_location: root_path) #アクション前のページに移動
  end

  def destroy
    book = Book.find(params[:book_id])
    favorite = current_user.favorites.find_by(book_id: book.id)
    favorite.destroy
    redirect_back(fallback_location: root_path)
  end

end

app/controllers/homes_controller.rb
class HomesController < ApplicationController

  def home
  end
  def about
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
    @books = @user.books
    @book = Book.new
  end

  def index
    @user = current_user
    @users = User.all
    @book = Book.new
  end


  def edit
    @user = User.find(params[:id])
    if @user.id == current_user.id
      render :edit
    else
      redirect_to user_path(current_user.id)
    end
  end


  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
    redirect_to user_path(@user.id), notice: "You have updated book successfully"
    else
      render :edit
    end
  end


  private

  def user_params
    params.require(:user).permit(:name, :profile_image, :introduction)
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/book_comments_helper.rb
module BookCommentsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/_list.html.erb
<h2>User info</h2>
<%= attachment_image_tag user, :profile_image, :fill, 100, 100, format: 'jpeg', fallback: "no_image.jpg" %>

<table class="table">
  <tbody>

		<tr>
			<th>name</th>
			<th><%= user.name %></th>
		</tr>

		<tr>
			<th>introduction</th>
			<th><%= user.introduction %></th>
		</tr>

	</tbody>
</table>

<button type = "button">
<% if user.id == current_user.id %>
    <%= link_to  edit_user_path(user) do %>
    <i class="fas fa-user-cog"></i>
    <% end %>
<% else %>
    <%= link_to books_path do %>
    <i class="fas fa-user-cog"></i>
    <% end %>
<% end %>
</button>

app/views/books/_list2.html.erb
<%= form_with model: @book, local:true do |f| %>

 <% if @book.errors.any? %>
   <h3><%= @book.errors.count %>件のerrorsが発生しました</h3>
   <% @book.errors.full_messages.each do |message| %>
     <li><%= message %></li>
   <% end %>
 <% end %>

<h2>New book</h2>

 <div class="form-group">
   <label for="book_title">Title</label>
   <%= f.text_field :title, class: "form-control" %>
 </div>

 <div class="form-group">
   <label for="book_opinion">Opinion</label>
   <%= f.text_area :body, class: "form-control" %>
 </div>

 <div class="form-group">
   <%= f.submit "Create Book", class: "btn btn-success" %>
 </div>

<% end %>

app/views/books/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-8 offset-md-1 mx-auto">

      <h1>Editing Book</h1>
      <div id="error_explanation">
        <% if @book.errors.any? %>
          <h3><%= @book.errors.count %>件のerrorsが発生しました</h3>
          <% @book.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        <% end %>
    </div>

      <%= form_with model:@book, local: true do |f| %>

      <div class="form-group">
        <label for="book_title">Title</label>
        <%= f.text_field :title, class: "form-control" %>
      </div>

      <div class="form-group">
        <label for="book_opinion">Opinion</label>
        <%= f.text_area :body, class: "form-control" %>
      </div>

      <div class="form-group">
        <%= f.submit "Update Book", class: "btn btn-success" %>
      </div>

      <% end %>
      <%= link_to "Show", book_path(@book) %>
      |
      <%= link_to "Back", books_path %>
    </div>
  </div>
</div>

app/views/books/index.html.erb
<div class="container">
	<div class="row">

		<div class="col-md-3">
			<!-- render 'list',user:@user -->
			<h2>User info</h2>
			<%= attachment_image_tag @user, :profile_image, :fill, 100, 100, format: 'jpeg', fallback: "no_image.jpg" %>

			<table class="table">
			  <tbody>

					<tr>
						<th>name</th>
						<th><%= @user.name %></th>
					</tr>

					<tr>
						<th>introduction</th>
						<th><%= @user.introduction %></th>
					</tr>

				</tbody>
			</table>

			<button type = "button">
			<% if @user.id == current_user.id %>
			    <%= link_to  edit_user_path(@user) do %>
			    <i class="fas fa-user-cog"></i>
			    <% end %>
			<% else %>
			    <%= link_to books_path do %>
			    <i class="fas fa-user-cog"></i>
			    <% end %>
			<% end %>
			</button>
			<!-- render 'list2',book:@book -->
			<%= form_with model: @book, local:true do |f| %>

			  <% if @book.errors.any? %>
			    <h3><%= @book.errors.count %>件のerrorsが発生しました</h3>
			    <% @book.errors.full_messages.each do |message| %>
			     <li><%= message %></li>
			    <% end %>
			  <% end %>

				<h2>New book</h2>

				<div class="form-group">
				  <label for="book_title">Title</label>
				  <%= f.text_field :title, class: "form-control" %>
				</div>

				<div class="form-group">
				  <label for="book_opinion">Opinion</label>
				  <%= f.text_area :body, class: "form-control" %>
				</div>

				<div class="form-group">
				  <%= f.submit "Create Book", class: "btn btn-success" %>
				</div>

			<% end %>
		</div>

		<div class="col-md-8 offset-md-1">
			<h2>Books</h2>
      <table class="table table-hover table-inverse">

	      <thead>
		      <tr>
		      	<th></th>
			      <th>Title</th>
			      <th>Opinion</th>
			      <th colspan="3"></th>
		      </tr>
	      </thead>

	      <tbody>
	        <% @books.each do |book| %>
		      <tr>

			      <td>
			      	<%= link_to user_path(book.user.id) do %>
				  	  <%= attachment_image_tag book.user, :profile_image, size: "40x40" , fallback: "no_image.jpg", class: "img-circle pull-left profile-thumb" %>
				      <% end %>
			      </td>
			      <td><%= link_to book.title, book_path(book.id) %></td>
			      <td><%= book.body %></td>
			      <td> <!--いいね機能-->
			    	<% if book.favorited_by?(current_user) %> <!--既にいいねされていたら-->
				      <%= link_to book_favorites_path(book), method: :delete do %>
				        <i class="fas fa-heart"></i>
				        <%= book.favorites.count %> いいね
				      <% end %>
				    <% else %>
				      <%= link_to book_favorites_path(book), method: :post do %>
				        <i class="fas fa-heart"></i>
				        <%= book.favorites.count %> いいね
				      <% end %>
				    <% end %>
				  </td>

				  <td>コメント数：<%= book.book_comments.count %></td>
		      </tr>
	        <% end %>
	      </tbody>
      </table>
		</div>
  </div>
</div>

app/views/books/new.html.erb
<h1>New book</h1>

<%= form_with model: @book, local:true do |f| %>

  <% if @book.errors.any? %>
		<h3><%= @book.errors.count %>件のerrorsが発生しました</h3>
		<% @book.errors.full_messages.each do |message| %>
		  <li><%= message %></li>
		<% end %>
	<% end %>

  <div class="form-group">
    <label for="book_title">Title</label>
    <%= f. text_field :title, class: "form-control"%>
  </div>

  <div class="form-group">
    <label for="book_opinion">Opinion</label>
    <%= f.text_area :body, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.submit "Create Book", class: "btn btn-success" %>
  </div>

<% end %>

app/views/books/show.html.erb
<div class="container">
	<div class="row">

		<div class="col-md-3">
      <!-- render 'list',user:@user -->
      <h2>User info</h2>
			<%= attachment_image_tag @user, :profile_image, :fill, 100, 100, format: 'jpeg', fallback: "no_image.jpg" %>

			<table class="table">
			  <tbody>

					<tr>
						<th>name</th>
						<th><%= @user.name %></th>
					</tr>

					<tr>
						<th>introduction</th>
						<th><%= @user.introduction %></th>
					</tr>

				</tbody>
			</table>

			<button type = "button">
			<% if @user.id == current_user.id %>
			    <%= link_to "edit", edit_user_path(@user) %>
			    <i class="fas fa-user-cog"></i>

			<% else %>
			    <%= link_to "edit", edit_user_path(@user) %>
			    <i class="fas fa-user-cog"></i>

            <% end %>
			</button>
      <!-- render 'list2',book:@books -->
      <%= form_with model: @books, local:true do |f| %>

		 <% if @books.errors.any? %>
		   <h3><%= @books.errors.count %>件のerrorsが発生しました</h3>
		   <% @books.errors.full_messages.each do |message| %>
		     <li><%= message %></li>
		   <% end %>
		 <% end %>

		<h2>New book</h2>

		 <div class="form-group">
		   <label for="book_title">Title</label>
		   <%= f.text_field :title, class: "form-control" %>
		 </div>

		 <div class="form-group">
		   <label for="book_opinion">Opinion</label>
		   <%= f.text_area :body, class: "form-control" %>
		 </div>

		 <div class="form-group">
		   <%= f.submit "Create Book", class: "btn btn-success" %>
		 </div>

		<% end %>

		</div>

		<div class="col-md-8 offset-md-1">
      <h2>Book detail</h2>

      <table class="table">
	      <tbody>
			  <tr>
				<td>
			    <%= attachment_image_tag @book.user, :profile_image, :fill, 60, 60, fallback: "no_image.jpg", class: "img-circle pull-left profile-thumb" %><br>
				  <%= link_to @user.name, user_path(@user.id) %>
			    </td>
			    <td><%= @book.title %></td>
				<td><%= @book.body %></td>
				<td>
				  <% if @book.user == current_user %>
				    <%= link_to "Edit", edit_book_path(@book.id), class:"btn btn-primary" %>
				  <% end %>
				</td>
			    <td>
			  	  <% if @book.user == current_user %>
				      <%= link_to "Destroy", book_path(@book), class:"btn btn-primary", method: :delete,"data-confirm" => "本当に削除しますか？" %>
				    <% end %>
			    </td>

			    <td> <!--いいね機能-->
		    	<% if @book.favorited_by?(current_user) %> <!--既にいいねされていたら-->
			      <%= link_to book_favorites_path(@book), method: :delete do %>
			        <i class="fas fa-heart"></i>
			        <%= @book.favorites.count %> いいね
			      <% end %>
			    <% else %>
			      <%= link_to book_favorites_path(@book), method: :post do %>
			        <i class="fas fa-heart"></i>
			        <%= @book.favorites.count %> いいね
			      <% end %>
			    <% end %>
				</td>
				<td> <!--コメントカウント-->
				  <p>コメント数：<%= @book.book_comments.count %></p>
				</td>
			  </tr>
        </tbody>
      </table>
      <h3>Comment</h3>
	    <table class="table">
	      <tbody>
	        <% @book.book_comments.each do |book_comment| %>
	        <tr>
	          <td>
	            <p><%= attachment_image_tag @book.user, :profile_image, format: "jpeg", size: "100x100", fallback: "no_image.jpeg" %></p>
	          </td>
	          <td>
	            <%= book_comment.user.name %>
	          </td>
	          <td>
	            <%= book_comment.created_at.strftime('%Y/%m/%d') %><%= book_comment.comment %>
	          </td>
	          <td>
	            <% if book_comment.user == current_user %>
	              <div class="comment-delete">
	                <%= link_to "Destroy", book_book_comment_path(book_comment.book, book_comment), class: "btn btn-sm btn-danger", method: :delete %>
	              </div>
	            <% end %>
	          </td>
	        <% end %>
	        </tr>
	      </tbody>
	    </table>
	    <div class="new-comment">
	      <%= form_with(model:[@book, @book_comment], local: true) do |f| %>
	        <%= f.text_area :comment, rows: '5' %>
	        <%= f.submit "Create Book comment" %>
	      <% end %>
	    </div>
    </div>
</div>

app/views/homes/about.html.erb
<div class="container">
  <h1>Welcome to
    <i class="fas fa-book"></i>
    Bookers!
  </h1>
</div>

app/views/homes/home.html.erb
<div class="body">
  <div class="container">

    <h1>welcome to <i class="fas fa-book"></i>Bookers!!
    </h1>

    <p>In <i class="fas fa-book"></i>Bookers
    </p>

    <p>you can share and exchange your opinions , inpressions ,and emotions</p>
    <p>about various books!</p>

    <p><%= link_to "Log in", new_user_session_path, class: "btn btn-info col-xs-10 col-xs-offset-1 sign-in" %></p>
    <p><%= link_to "Sign Up", new_user_registration_path, class:"btn btn-success col-xs-10 col-xs-offset-1 sign-in" %></p>

  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <script src="https://kit.fontawesome.com/77e29917b5.js" crossorigin="anonymous"></script>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <header>
      <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
          <a class="navbar-brand" href="/">
            <span>Bookers</span>
          </a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav ml-auto">
              <% if user_signed_in? %>
                <li class="nav-item">
                  <%= link_to "Home", user_path(current_user.id), class: "fas fa-home nav-link text-light" %>
                </li>
                <li class="nav-item">
                  <%= link_to "Users", users_path, class: "fas fa-users nav-link text-light" %>
                </li>
                <li class="nav-item">
                  <%= link_to "Books", books_path, class: "fas fa-book-open nav-link text-light" %>
                </li>
                <li class="nav-item">
                  <%= link_to "logout", destroy_user_session_path, method: :delete, class: "fas fa-sign-out-alt nav-link text-light" %>
                </li>
              <% else %>
                <li class="nav-item">
                  <%= link_to "Home", root_path, class: "fas fa-home nav-link text-light" %>
                </li>
                <li class="nav-item">
                  <%= link_to "About", home_about_path, class: "fas fa-link nav-link text-light" %>
                </li>
                <li class="nav-item">
                  <%= link_to "sign up", new_user_registration_path, class: "fas fa-user-plus nav-link text-light" %>
                </li>
                <li class="nav-item">
                  <%= link_to "login", new_user_session_path, class: "fas fa-sign-in-alt nav-link text-light" %>
                </li>
              <% end %>
            </ul>
          </div>
      </nav>
    </header>

    <div class="notice">
      <%= notice %>
    </div>

    <div class="container">
      <%= yield %>
    </div>

    <footer>
      <div class="container mt-5">
        <div class="row">
          <div class="mx-auto">
            CopyRight Infratop.inc
          </div>
        </div>
      </div>
    </footer>
  </body>
</html>

app/views/users/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-8 offset-md-1 mx-auto">
     <h2>User info</h2>
        <%= attachment_image_tag @user, :profile_image, :fill, 100, 100, format: 'jpeg', fallback: "no_image.jpg" %>

        <% if @user.errors.any? %>
          <h3><%= @user.errors.count %>件のerrorsが発生しました</h3>
          <% @user.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        <% end %>

        <%= form_with model: @user, local:true do |f| %>

          <div class="form-group">
            <label for="user_name">Name</label>
            <%= f.text_field :name, autofocus: true, class:"form-control" %>
          </div>

          <div class="form-group">
            <label for="user_image">Image</label>
            <%= f.attachment_field :profile_image, class:"form-control" %>
          </div>

          <div class="form-group">
            <label for="user_introduction">Introduction</label>
            <%= f.text_area :introduction, class:"form-control" %>
          </div>

          <div class="form-group">
            <%= f.submit "Update User", class:"btn btn-secondary" %>
          </div>

        <% end %>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<div class="container">

	<div class="row">

		<div class="col-md-3">
			<!-- render 'books/list',user:@user -->
			<h2>User info</h2>
			<%= attachment_image_tag @user, :profile_image, :fill, 100, 100, format: 'jpeg', fallback: "no_image.jpg" %>

			<table class="table">
			  <tbody>

					<tr>
						<th>name</th>
						<th><%= @user.name %></th>
					</tr>

					<tr>
						<th>introduction</th>
						<th><%= @user.introduction %></th>
					</tr>

				</tbody>
			</table>

			<button type = "button">
			<% if @user.id == current_user.id %>
			    <%= link_to  edit_user_path(@user) do %>
			    <i class="fas fa-user-cog"></i>
			    <% end %>
			<% else %>
			    <%= link_to books_path do %>
			    <i class="fas fa-user-cog"></i>
			    <% end %>
			<% end %>
			</button>
			<!-- render 'books/list2',book:@book -->
			<%= form_with model: @book, local:true do |f| %>

			 <% if @book.errors.any? %>
			   <h3><%= @book.errors.count %>件のerrorsが発生しました</h3>
			   <% @book.errors.full_messages.each do |message| %>
			     <li><%= message %></li>
			   <% end %>
			 <% end %>

			<h2>New book</h2>

			 <div class="form-group">
			   <label for="book_title">Title</label>
			   <%= f.text_field :title, class: "form-control" %>
			 </div>

			 <div class="form-group">
			   <label for="book_opinion">Opinion</label>
			   <%= f.text_area :body, class: "form-control" %>
			 </div>

			 <div class="form-group">
			   <%= f.submit "Create Book", class: "btn btn-success" %>
			 </div>

			<% end %>
		</div>

		<div class="col-md-8 offset-md-1">
      <h2>Users</h2>
	    <table class="table">
		    <thead>
			    <tr>
				    <th>image</th>
				    <th>name</th>
				    <th colspan=3></th>
			    </tr>
		    </thead>
		    <tbody>
			    <% @users.each do |user| %>
				    <tr>
					    <td><%= attachment_image_tag user, :profile_image, size: "40x40", fallback: "no_image.jpg", class: "img-circle pull-left profile-thumb" %></td>
					    <td><%= user.name %></td>
					    <td><%= link_to "Show", user_path(user.id) %></td>
				    </tr>
			    <% end %>
		    </tbody>
	  </table>
  </div>
</div>

app/views/users/show.html.erb
<div class="container">
	<div class="row">

		<div class="col-md-3">
			<!-- render 'books/list',user:@user -->
			<h2>User info</h2>
      <%= attachment_image_tag @user, :profile_image, :fill, 100, 100, format: 'jpeg', fallback: "no_image.jpg" %>

      <table class="table">
        <tbody>

      		<tr>
      			<th>name</th>
      			<th><%= @user.name %></th>
      		</tr>

      		<tr>
      			<th>introduction</th>
      			<th><%= @user.introduction %></th>
      		</tr>

      	</tbody>
      </table>

      <button type = "button">
      <% if @user.id == current_user.id %>
          <%= link_to edit_user_path(@user) do %>
          <i class="fas fa-user-cog"></i>
          <% end %>
      <% else %>
          <%= link_to edit_user_path(@user) do %>
          <i class="fas fa-user-cog"></i>
          <% end %>
      <% end %>
      </button>
			<!-- render 'books/list2',book:@book -->
			<%= form_with model: @book, local:true do |f| %>

       <% if @book.errors.any? %>
         <h3><%= @book.errors.count %>件のerrorsが発生しました</h3>
         <% @book.errors.full_messages.each do |message| %>
           <li><%= message %></li>
         <% end %>
       <% end %>

      <h2>New book</h2>

       <div class="form-group">
         <label for="book_title">Title</label>
         <%= f.text_field :title, class: "form-control" %>
       </div>

       <div class="form-group">
         <label for="book_opinion">Opinion</label>
         <%= f.text_area :body, class: "form-control" %>
       </div>

       <div class="form-group">
         <%= f.submit "Create Book", class: "btn btn-success" %>
       </div>

      <% end %>
		</div>

    <div class="col-md-8 offset-md-1">
      <h2>Books</h2>
      <table class="table table-hover table-inverse">
	    <thead>
	      <tr>
	        <th></th>
	        <th>Title</th>
	        <th>Opinion</th>
	        <th colspan="3"></th>
	      </tr>
        </thead>

	    <tbody>
	      <% @books.each do |book| %>
		      <tr>

            <td>
            <%= link_to user_path(book.user.id) do %>
              <%= attachment_image_tag @user, :profile_image, size: "40x40", fallback: "no_image.jpeg" %>
            <% end %>
            </td>

            <td>
            <%= link_to book_path(book.id) do %>
              <%= book.title %>
            <% end %>
            </td>

            <td>
            <%= link_to book_path(book.id) do %>
              <%= book.body %>
            <% end %>
            </td>

            <td>コメント数：<%= book.book_comments.count %></td>

          </tr>
	      <% end %>
	    </tbody>
      </table>
    </div>
  </div>
</div>